name: ユニットテストの実行

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  test:
    name: ユニットテストの実行
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # 後続の操作では認証情報を使用しないため、破棄するように設定
          persist-credentials: false

      - name: Node.js のセットアップ
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: package.json

      - name: 依存関係のインストール
        run: npm ci

      - name: ユニットテストの実行
        run: npm test
